import { precacheAndRoute } from "workbox-precaching";

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Push notification handler
self.addEventListener("push", (event) => {
  if (!event.data) return;

  let payload;
  try {
    payload = event.data.json();
  } catch {
    payload = { title: "Family Shield", body: event.data.text() };
  }

  const options = {
    body: payload.body,
    icon: "/icon-192.png",
    badge: "/icon-192.png",
    vibrate: [200, 100, 200],
    tag: payload.tag || "default",
    data: { url: payload.url || "/" },
  };

  // SOS notifications stay until dismissed
  if (payload.requireInteraction) {
    options.requireInteraction = true;
    options.vibrate = [500, 200, 500, 200, 500];
  }

  event.waitUntil(self.registration.showNotification(payload.title, options));
});

// Click handler — focus existing window or open new
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data?.url || "/";

  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if (client.url.includes(self.location.origin) && "focus" in client) {
          return client.focus();
        }
      }
      return self.clients.openWindow(url);
    })
  );
});
